services:
  - type: web
    name: webreg-to-ics
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: gunicorn app:app
